---
title: "Mortality"
output: 
html_notebook: default
---

# Install library
```{r}
library(tidyverse)
```

# Set up working directory
```{r setup}
knitr::opts_knit$set(root.dir = normalizePath("/Users/hannahjiang/Documents/github/hj-adj-summer22/final-project"))
```

# Import, modify and clean up the state prisons mortality data
```{r}
msfp_original <- read_csv("data/msfp0119stt16.csv");
mortality <- msfp_original[c(11,14:63), c(2:13)];

names(mortality) <- c("State", "All_causes", "Heart_disease", "Cancer", "Liver_disease", "AIDS_related", "Respiratory_disease", "All_other_illnesses", "Suicide", "Drug_alcohol_intoxication", "Accident", "Homicide");
mortality <- mortality[-c(1), ];

mortality[mortality == "Alaska/g"] <- "Alaska";
mortality[mortality == "Connecticut/h"] <- "Connecticut";
mortality[mortality == "Delaware/h"] <- "Delaware";
mortality[mortality == "Hawaii/h"] <- "Hawaii";
mortality[mortality == "Rhode Island/h"] <- "Rhode Island";
mortality[mortality == "Vermont/h"] <- "Vermont"

replaceCommas<-function(x){
  x<-as.numeric(gsub("\\,", "", x))
}

```

# I can't sort it out. The reference most relevant to my situation that I found: https://stackoverflow.com/questions/49910861/removing-comma-from-numbers-in-r


